-- 固定取数
CALL EXT_TMP.SP_GOODS_CHOOSE_V1_0('20181231')
-- 每月固定取数脚本
SELECT  GOODS_CODE,
		GOODS_NAME,
		PURC_CLAS_LEV1_CODE,  --采购分类一级编码
		PURC_CLAS_LEV1_NAME,  --采购分类一级名称
		PURC_CLAS_LEV2_CODE,  --采购分类二级编码
		PURC_CLAS_LEV2_NAME,  --采购分类二级名称
		PURC_CLAS_LEV3_CODE,  --采购分类三级编码
		PURC_CLAS_LEV3_NAME, --采购分类三级编码
		COST_PRICE, --成本价
		MEMBER_PRICE,  --会员价
		STORE_QUATITY --库存
	FROM EXT_TMP.GOODS_CHOOSE_V1_0
	WHERE IS_NEW_PROD='Y';
	

-- 无图片商品取数20190117

CALL EXT_TMP.SP_GOODS_CHOOSE_V1_0('20190117')

SELECT A.GOODS_CODE,GOODS_NAME,
		PURC_CLAS_LEV1_CODE,
		PURC_CLAS_LEV1_NAME,  --采购分类一级名称
		PURC_CLAS_LEV2_CODE,  --采购分类二级编码
		PURC_CLAS_LEV2_NAME,  --采购分类二级名称
		PURC_CLAS_LEV3_CODE,  --采购分类三级编码
		PURC_CLAS_LEV3_NAME, --采购分类三级编码
		STORE_QUATITY --库存
FROM "EXT_TMP"."GOODS_CODE_NO_PIC" A
LEFT JOIN 
(SELECT GOODS_CODE,GOODS_NAME,
		PURC_CLAS_LEV1_CODE,  --采购分类一级编码
		PURC_CLAS_LEV1_NAME,  --采购分类一级名称
		PURC_CLAS_LEV2_CODE,  --采购分类二级编码
		PURC_CLAS_LEV2_NAME,  --采购分类二级名称
		PURC_CLAS_LEV3_CODE,  --采购分类三级编码
		PURC_CLAS_LEV3_NAME, --采购分类三级编码
		STORE_QUATITY
from EXT_TMP.GOODS_CHOOSE_V1_0)b
on a.goods_code=b.goods_code